## Numpy

In [145]:
import numpy as np

In [146]:
myArray = np.array([[1,2,3],
                    [4,5,6]])

In [147]:
myArray

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
# operasi satu bilangan
addMyArray = myArray + 2
reduceMyArray = myArray - 2
square = myArray ** 2
print('my array', myArray)
print('add', addMyArray)
print('reduce', reduceMyArray)
print('square', square)

my array [[1 2 3]
 [4 5 6]]
add [[3 4 5]
 [6 7 8]]
reduce [[-1  0  1]
 [ 2  3  4]]
square [[ 1  4  9]
 [16 25 36]]


In [149]:
# boolean
isMyArrayMoreThan3 = myArray > 4

isMyArrayMoreThan3

array([[False, False, False],
       [False,  True,  True]])

In [150]:
# filtering
valuseMoreThan3c = myArray[myArray > 4]
print(valuseMoreThan3c)

[5 6]


In [151]:
array2D = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])

In [152]:
array2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [153]:
# ukuran array
print(array2D.shape)

(3, 4)


In [154]:
# try to get 4
print(array2D[0,3])

4


In [155]:
# rentang array 
print(array2D[:,1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [156]:
array2D[0:][0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [157]:
# import data from csv
myStudentData = np.genfromtxt('./data.csv', skip_header=1, delimiter=',', filling_values=40)

In [158]:
myStudentData

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.],
       [40., 60., 55., 75.]])

In [159]:
# nilai terbesar setiap mapel
maxInclass= np.amax(myStudentData, axis=0)
maxInclass

array([75., 80., 90., 90.])

In [166]:
# nilai rata2 setiap mapel
rata2SiswaSetiapMapel = np.mean(myStudentData, axis=0)
rata2SiswaSetiapMapel

array([61. , 71.4, 68.2, 65.8])

In [161]:
myStudentData = np.append(myStudentData, [[55,65,56,66]], axis=0)
myStudentData

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.],
       [40., 60., 55., 75.],
       [55., 65., 56., 66.]])

In [167]:
minInclass = np.min(myStudentData, axis=0)
minInclass

array([40., 60., 55., 30.])

In [168]:
medianInclass = np.median(myStudentData, axis=0)
medianInclass

array([65., 75., 60., 68.])

In [169]:
avgInclass = np.average(myStudentData, axis=0)
avgInclass

array([61. , 71.4, 68.2, 65.8])

In [170]:
jumlahNilaiInclass = np.sum(myStudentData, axis=0)
jumlahNilaiInclass

array([305., 357., 341., 329.])

In [171]:
[y,x] = myStudentData.shape

In [199]:
myStudentData[:y,:x]

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.],
       [40., 60., 55., 75.],
       [55., 65., 56., 66.]])

In [198]:
myNewStudent = np.delete(myStudentData, [4], axis=0)
myNewStudent

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.],
       [40., 60., 55., 75.]])

In [203]:
# reshape and resize
newReshape = np.reshape(myStudentData,[10,2])
newResize = np.resize(myStudentData,[10,3])
print(newReshape)
print('========\n',newResize)

[[70. 75.]
 [80. 30.]
 [75. 80.]
 [90. 68.]
 [65. 77.]
 [60. 90.]
 [40. 60.]
 [55. 75.]
 [55. 65.]
 [56. 66.]]
 [[70. 75. 80.]
 [30. 75. 80.]
 [90. 68. 65.]
 [77. 60. 90.]
 [40. 60. 55.]
 [75. 55. 65.]
 [56. 66. 70.]
 [75. 80. 30.]
 [75. 80. 90.]
 [68. 65. 77.]]


In [206]:
# array of eye
eyes = np.eye(5,5)
print(eyes)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [207]:
array_1 = np.array([[1,2,3],
                    [4,5,6]])
array_2 = np.array([[1,5,3],
                    [4,2,3]])
array_3 = np.array([[4,6,2],
                    [1,2,6]])

In [215]:
# perlalian matrix
arr1Kaliarr2 = np.dot(array_1,np.transpose(array_3))
arr1Kaliarr2

array([[22, 23],
       [58, 50]])

#### 1d to 2d

In [221]:
oneDarray = np.array([1,2,3,4,5,6,7,8,9,0])
twoDarray = oneDarray.reshape(2,5)

In [222]:
twoDarray

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [223]:
[y,x] = twoDarray.shape
backTOoneD = twoDarray.reshape(1,x*y)[0]
backTOoneD

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [228]:
array_1 = np.array([[1,2,3],
                    [4,5,6]])
array_2 = np.array([[1,5,3],
                    [4,2,3]])
array_3 = np.array([[4,6],
                    [1,2]])

#vstaack
v_stacck = np.vstack((array_1, array_2))
h_stacck = np.hstack((array_1, array_2))

In [225]:
v_stacck

array([[1, 2, 3],
       [4, 5, 6],
       [1, 5, 3],
       [4, 2, 3]])

In [226]:
h_stacck

array([[1, 2, 3, 1, 5, 3],
       [4, 5, 6, 4, 2, 3]])

In [229]:
h_stacckArr3 = np.hstack((array_1, array_3))
h_stacckArr3

array([[1, 2, 3, 4, 6],
       [4, 5, 6, 1, 2]])

In [234]:
# lenaImg = .imgread('./lena.jpeg')